version: "3.9"
services:
  clickhouse:
    image: clickhouse/clickhouse-server
    ports:
      - "28123:8123"
      - "29000:9000"
    volumes:
      - clickhouse_data:/var/lib/clickhouse/
volumes:
  clickhouse_data:
